---
- name: Play de serviços de windows
  hosts: windows.automation.here
  gather_facts: True
  tasks:
    - name: Pega o status
      ansible.windows.win_service_info:
        name: Themes
      register: serv_status

    - name: exibe
      ansible.builtin.debug:
        var: serv_status


